# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ba143eb6c23ca0bfff705361fa96b6e6339876e0cb03e57540739ea0106220e7d23b26dc8d2c670fb7c9622d564241c913944ed9bb0a3bc7eb4b3bf85768bda

test:
  secret_key_base: b56789da6c439262f44428b58704d14fdfe0f919c870dff125c549230e47612846ffee9344b23af5eea176c512fa16f0182d93bea33cdf014354b16b917e7b0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
